<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "infochy_cobject"
 *
 * Auto generated by Extension Builder 2017-02-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Plugin Extbase Fluid TypoScript Include Example',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Micha Barthel',
	'author_email' => 'mb@infochy.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);