<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "infochy_helper"
 *
 * Auto generated by Extension Builder 2016-11-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Helper-Library for Frontend-Editing Extensions',
    'description' => 'Helper-Library Frontend-Editing Extensions',
    'category' => 'plugin',
    'author' => 'Micha Barthel',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.3',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.6.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
