<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "infochy_multilang"
 *
 * Auto generated by Extension Builder 2017-12-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Extbase Multilanguage',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Micha Barthel',
    'author_email' => 'mb@infochy.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
